;;;;+ Extra

(el-get-bundle gist:9580569:east-asian-ambiguous)
(el-get-bundle tabbar)
(el-get-bundle powerline)
(el-get-bundle flycheck-color-mode-line)
(el-get-bundle expand-region)
(el-get-bundle multiple-cursors)
(el-get-bundle yascroll)
(el-get-bundle direx)
(el-get-bundle go-direx)
(el-get-bundle go-autocomplete)
(el-get-bundle ac-ispell)
(el-get-bundle projectile)
(el-get-bundle helm-projectile)
(el-get-bundle ggtags)
(el-get-bundle open-junk-file)
(el-get-bundle lispxmp)
(el-get-bundle gist)
(el-get-bundle typescript-mode)
(el-get-bundle tide)
(el-get-bundle jedi)
(el-get-bundle yasnippet-snippets)
(el-get-bundle vimrc-mode)
;; (el-get-bundle nlinum)
(el-get-bundle k-talo/smooth-scroll.el :name smooth-scroll)
(el-get-bundle emacs-jp/replace-colorthemes)
(el-get-bundle kaushalmodi/ox-hugo)
(el-get-bundle sfus/org-screenshot :name org-attach-screenshot)
(el-get-bundle org-pomodoro)
;; ;;(el-get-bundle e2wm)
(el-get-bundle sql-upcase)
(el-get-bundle alex-hhh/emacs-sql-indent :name sql-indent)
(el-get-bundle sfus/text-adjust.el :name text-adjust)
(el-get-bundle skuro/plantuml-mode)
